import { authFailureResponse, authenticateRequest } from "./utils/auth";
import fs from "fs";
import path from "path";

// Cache fromToPositionIndexed in memory on cold start
let fromToIndexCache = null;

async function loadFromToIndex() {
  if (!fromToIndexCache) {
    // Try local file first (for development)
    // TODO: Once eco.json.tooling publishes this to eco.json GitHub, remove local fallback
    const localPath = path.resolve("data/fromToPositionIndexed.json");

    try {
      if (fs.existsSync(localPath)) {
        console.log("Loading fromToPositionIndexed.json from local file");
        const data = fs.readFileSync(localPath, "utf-8");
        fromToIndexCache = JSON.parse(data);
        return fromToIndexCache;
      }
    } catch (err) {
      console.warn(
        "Failed to load local file, falling back to GitHub:",
        err.message,
      );
    }

    // Fallback: Download from eco.json GitHub repo (generated by eco.json.tooling)
    console.log("Loading fromToPositionIndexed.json from GitHub");
    const url =
      "https://raw.githubusercontent.com/JeffML/eco.json/master/fromToPositionIndexed.json";
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(
        `Failed to fetch fromToPositionIndexed.json: ${response.status}`,
      );
    }
    fromToIndexCache = await response.json();
  }
  return fromToIndexCache;
}

//return position part of FEN string
const pos = (fen) => fen.split(" ")[0];

export const handler = async (event) => {
  if (!authenticateRequest(event)) return authFailureResponse;

  const fen = event.queryStringParameters?.fen;

  if (!fen) {
    return {
      statusCode: 400,
      body: JSON.stringify({ error: "Missing fen parameter" }),
    };
  }

  // Load index from GitHub (cached after first load)
  const json = await loadFromToIndex();
  const position = pos(fen);

  const result = {
    next: json.to[position] ?? [],
    from: json.from[position] ?? [],
  };

  return {
    statusCode: 200,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST",
    },
    body: JSON.stringify(result),
  };
};
