import { authFailureResponse, authenticateRequest } from './utils/auth'

// Cache scores in memory on cold start
let scoresCache = null;

async function loadScores() {
  if (!scoresCache) {
    // Download from eco.json GitHub repo (generated by eco.json.tooling)
    const url = 'https://raw.githubusercontent.com/JeffML/eco.json/master/scores.json';
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch scores.json: ${response.status}`);
    }
    scoresCache = await response.json();
  }
  return scoresCache;
}

export const handler = async (event) => {
    if (!authenticateRequest(event)) return authFailureResponse;
    
    if (event.httpMethod !== 'POST') {
        return {
            statusCode: 400,
            body: 'You are not using an HTTP POST method for this endpoint.',
            headers: { Allow: 'POST' },
        };
    }

    let body;
    if (
        event.headers['content-type'] &&
        event.headers['content-type'].includes('application/json')
    ) {
        body = JSON.parse(event.body);
    }

    try {
        const {fen, from, next} = body

        // Load scores from GitHub (cached after first load)
        const scores = await loadScores();

        // Look up score for the given FEN
        const score = scores[fen];

        if (score === undefined) {
            return {
                statusCode: 404,
                body: JSON.stringify({
                    error: 'Score not found for this position',
                    fen,
                }),
            };
        }

        const nextScores = next.map(fen => scores[fen])
        const fromScores = from.map(fen => scores[fen])

        return {
            statusCode: 200,
            headers: {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*', // Adjust for production
                'Cache-Control': 'public, max-age=3600', // Cache for 1 hour
            },
            body: JSON.stringify({
                score,
                nextScores,
                fromScores
            }),
        };
    } catch (error) {
        console.error('Error fetching score:', error);

        return {
            statusCode: 500,
            body: JSON.stringify({
                error: 'Internal server error',
                message: error.message,
            }),
        };
    }
};
