import "./App.css";
import "./stylesheets/about.css";

const About = () => (
    <div className="about">
        <p>
            Fenster is a comprehensive chess opening reference site, the basis
            of which is <a href="">eco.json</a>. It is not a repository of chess
            games, though Fenster is capable of pulling in associated opening
            information from FICS, lichess, and Shredder databases if requested.
        </p>
        <h2>The Search Page</h2>
        The Search Page is the default page. You can locate and opening by
        entering moves in the board at left, or entering a FEN or PGN in the
        text box below the board. When (and if) an opening is located,
        information about it is displayed on the right side. This includes the
        opening name, its ECO code and what variations, if any, branch off from
        this opening position. Sometimes, an opening position can be arrived at
        by difference move sequences; these will be displayed below the
        variations at right.
        <p>
            In most cases there is an evaluation given for each variation
            displayed at right. These scores are generated by Stockfish after
            running for 1.5 seconds on an Intel i7 processor. Variations can be
            sorted by evaluation (absolute value) as well as by opening name.
        </p>
        <p>
            At the upper right, available on all pages, is a selector to include
            information of FICS, lichess, or Shredder. The information, when
            selected, will include how many games with the current position can
            be found on each side, and what the white win, black win, and draw
            statistics are.
        </p>
        <h2>The PGN Import Page</h2>
        This page shows downloads available from The Week in Chess website. (You
        have also the option to upload a PGN file from your computer.) By
        clicking on onw of the TWIC links, infomation about openings in the PGN
        file is displayed, as well at the players and rating information. You
        can sort the list of players by name, rating (ELO) or title.
        <p>
            In addition to the Summary tab, the is the Games tab. This will
            display information about each game in the PGN file. If you click on
            the Opening name, it will display what Fenster know the opening name
            (which may be different from what is called in the PGN file), as
            well as the move sequence. If one or more of the sites in the upper
            right are selected the opening name as known to each site is
            displayed, as well as aggregate statistics for that opening.
        </p>
    </div>
);

export default About;
