const opening2 = {
    "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1": {
        eco: "B00",
        name: "King's Pawn Game",
        moves: "1. e4",
        next: [
            {
                name: "Nimzowitsch Defense",
                moves: "1. e4 Nc6",
                score: 0.53,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Lemming Defense",
                moves: "1. e4 Na6",
                score: 1.05,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Hippopotamus Defense",
                moves: "1. e4 Nh6",
                score: 1.19,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Alekhine Defense",
                moves: "1. e4 Nf6",
                score: 0.84,
                eco: "B02",
                __typename: "OpeningNext",
            },
            {
                name: "St. George Defense",
                moves: "1. e4 a6",
                score: 0.75,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Ware Defense",
                moves: "1. e4 a5",
                score: 0.99,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Owen Defense",
                moves: "1. e4 b6",
                score: 0.98,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Caro-Kann Defense",
                moves: "1. e4 c6",
                score: 0.37,
                eco: "B10",
                __typename: "OpeningNext",
            },
            {
                name: "Sicilian Defense",
                moves: "1. e4 c5",
                score: 0.27,
                eco: "B20",
                __typename: "OpeningNext",
            },
            {
                name: "Pirc Defense",
                moves: "1. e4 d6",
                score: 0.51,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Scandinavian Defense",
                moves: "1. e4 d5",
                score: 0.62,
                eco: "B01",
                __typename: "OpeningNext",
            },
            {
                name: "French Defense",
                moves: "1. e4 e6",
                score: 0.25,
                eco: "C00",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game",
                moves: "1. e4 e5",
                score: 0.43,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "Barnes Defense",
                moves: "1. e4 f6",
                score: 1.27,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Duras Gambit",
                moves: "1. e4 f5",
                score: 2.41,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Modern Defense",
                moves: "1. e4 g6",
                score: 0.84,
                eco: "B06",
                __typename: "OpeningNext",
            },
            {
                name: "Borg Defense",
                moves: "1. e4 g5",
                score: 1.88,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Carr Defense",
                moves: "1. e4 h6",
                score: 0.62,
                eco: "B00",
                __typename: "OpeningNext",
            },
            {
                name: "Goldsmith Defense",
                moves: "1. e4 h5",
                score: 1.2,
                eco: "B00",
                __typename: "OpeningNext",
            },
        ],
        from: [],
        aliases: ["King's Pawn", "King's Pawn"],
        score: 0.44,
        __typename: "Opening2",
    },
    "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2": {
        eco: "C20",
        name: "King's Pawn Game",
        moves: "1. e4 e5",
        next: [
            {
                name: "King's Pawn Game: Mengarini's Opening",
                moves: "1. e4 e5 2. a3",
                score: 0,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Opening",
                moves: "1. e4 e5 2. b3",
                score: -0.34,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: MacLeod Attack",
                moves: "1. e4 e5 2. c3",
                score: -0.42,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "English Opening: The Whale",
                moves: "1. e4 e5 2. c4",
                score: -0.16,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Leonardis Variation",
                moves: "1. e4 e5 2. d3",
                score: 0,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "Center Game",
                moves: "1. e4 e5 2. d4",
                score: 0.07,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: King's Head Opening",
                moves: "1. e4 e5 2. f3",
                score: -0.67,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "King's Gambit",
                moves: "1. e4 e5 2. f4",
                score: -0.34,
                eco: "C30",
                __typename: "OpeningNext",
            },
            {
                name: "Vienna Game",
                moves: "1. e4 e5 2. Nc3",
                score: 0.24,
                eco: "C25",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Napoleon Attack",
                moves: "1. e4 e5 2. Qf3",
                score: -0.26,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Wayward Queen Attack",
                moves: "1. e4 e5 2. Qh5",
                score: -0.2,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "Bongcloud Attack",
                moves: "1. e4 e5 2. Ke2",
                score: -1,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Tortoise Opening",
                moves: "1. e4 e5 2. Bd3",
                score: -0.13,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "Bishop's Opening",
                moves: "1. e4 e5 2. Bc4",
                score: 0.22,
                eco: "C23",
                __typename: "OpeningNext",
            },
            {
                name: "Portuguese Opening",
                moves: "1. e4 e5 2. Bb5",
                score: -0.18,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Alapin Opening",
                moves: "1. e4 e5 2. Ne2",
                score: -0.12,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "King's Knight Opening",
                moves: "1. e4 e5 2. Nf3",
                score: 0.3,
                eco: "C40",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game (i)",
                moves: "1. e4 e5 2. Qe2",
                score: -0.39,
                eco: "C20",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game (i)",
                moves: "1. e4 e5 2. Qg4",
                score: -0.75,
                eco: "C20",
                __typename: "OpeningNext",
            },
        ],
        from: [
            {
                name: "King's Pawn Game",
                moves: "1. e4",
                __typename: "OpeningNext",
            },
        ],
        aliases: ["Open Game"],
        score: 0.43,
        __typename: "Opening2",
    },
    "rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2": {
        eco: "C40",
        name: "King's Knight Opening",
        moves: "1. e4 e5 2. Nf3",
        next: [
            {
                name: "King's Knight Opening: Normal Variation",
                moves: "1. e4 e5 2. Nf3 Nc6",
                score: 0.42,
                eco: "C44",
                __typename: "OpeningNext",
            },
            {
                name: "Gunderam Defense",
                moves: "1. e4 e5 2. Nf3 Qe7",
                score: 0.95,
                eco: "C40",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: McConnell Defense",
                moves: "1. e4 e5 2. Nf3 Qf6",
                score: 1.26,
                eco: "C40",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Busch-Gass Gambit",
                moves: "1. e4 e5 2. Nf3 Bc5",
                score: 1.87,
                eco: "C40",
                __typename: "OpeningNext",
            },
            {
                name: "Russian Game",
                moves: "1. e4 e5 2. Nf3 Nf6",
                score: 0.28,
                eco: "C42",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Gunderam Gambit",
                moves: "1. e4 e5 2. Nf3 c6",
                score: 1.11,
                eco: "C40",
                __typename: "OpeningNext",
            },
            {
                name: "Sicilian Defense: Jalalabad Variation",
                moves: "1. e4 c5 2. Nf3 e5",
                score: 1.71,
                eco: "B27",
                __typename: "OpeningNext",
            },
            {
                name: "Philidor Defense",
                moves: "1. e4 e5 2. Nf3 d6",
                score: 0.43,
                eco: "C41",
                __typename: "OpeningNext",
            },
            {
                name: "Elephant Gambit",
                moves: "1. e4 e5 2. Nf3 d5",
                score: 0.81,
                eco: "C40",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Damiano Defense",
                moves: "1. e4 e5 2. Nf3 f6",
                score: 2.4,
                eco: "C40",
                __typename: "OpeningNext",
            },
            {
                name: "Latvian Gambit",
                moves: "1. e4 e5 2. Nf3 f5",
                score: 1.08,
                eco: "C40",
                __typename: "OpeningNext",
            },
        ],
        from: [
            {
                name: "King's Pawn Game",
                moves: "1. e4 e5",
                __typename: "OpeningNext",
            },
        ],
        aliases: ["Open Game"],
        score: 0.3,
        __typename: "Opening2",
    },
    "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3": {
        eco: "C44",
        name: "King's Knight Opening: Normal Variation",
        moves: "1. e4 e5 2. Nf3 Nc6",
        next: [
            {
                name: "Irish Gambit",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Nxe5",
                score: -2.66,
                eco: "C44",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Pachman Wing Gambit",
                moves: "1. e4 e5 2. Nf3 Nc6 3. b4",
                score: -0.88,
                eco: "C44",
                __typename: "OpeningNext",
            },
            {
                name: "Ponziani Opening",
                moves: "1. e4 e5 2. Nf3 Nc6 3. c3",
                score: 0.06,
                eco: "C44",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Dresden Opening",
                moves: "1. e4 e5 2. Nf3 Nc6 3. c4",
                score: -0.34,
                eco: "C44",
                __typename: "OpeningNext",
            },
            {
                name: "Open Game: Inverted Philidor",
                moves: "1. e4 e5 2. Nf3 Nc6 3. d3",
                score: 0,
                eco: "C44",
                __typename: "OpeningNext",
            },
            {
                name: "Scotch Game",
                moves: "1. e4 e5 2. Nf3 Nc6 3. d4",
                score: 0.28,
                eco: "C44",
                __typename: "OpeningNext",
            },
            {
                name: "King's Knight Opening: Konstantinopolsky",
                moves: "1. e4 e5 2. Nf3 Nc6 3. g3",
                score: 0.1,
                eco: "C44",
                __typename: "OpeningNext",
            },
            {
                name: "Three Knights Opening",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Nc3",
                score: 0.12,
                eco: "C46",
                __typename: "OpeningNext",
            },
            {
                name: "King's Pawn Game: Tayler Opening",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Be2",
                score: 0,
                eco: "C44",
                __typename: "OpeningNext",
            },
            {
                name: "Italian Game",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bc4",
                score: 0.24,
                eco: "C50",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5",
                score: 0.39,
                eco: "C60",
                __typename: "OpeningNext",
            },
        ],
        from: [
            {
                name: "King's Knight Opening",
                moves: "1. e4 e5 2. Nf3",
                __typename: "OpeningNext",
            },
        ],
        aliases: ["Open Game"],
        score: 0.42,
        __typename: "Opening2",
    },
    "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3": {
        eco: "C60",
        name: "Ruy Lopez",
        moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5",
        next: [
            {
                name: "Ruy Lopez: Vinogradov Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 Qe7",
                score: 0.98,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Lucena Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 Be7",
                score: 0.5,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Classical Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 Bc5",
                score: 0.71,
                eco: "C64",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Alapin Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 Bb4",
                score: 1.13,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Berlin Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 Nf6",
                score: 0.25,
                eco: "C65",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Cozio Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 Nge7",
                score: 0.5,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6",
                score: 0.29,
                eco: "C70",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Bulgarian Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a5",
                score: 0.59,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Rotary-Albany Gambit",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 b6",
                score: 0.87,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Steinitz Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 d6",
                score: 0.43,
                eco: "C62",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Spanish Countergambit",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 d5",
                score: 1.76,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Nürnberg Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 f6",
                score: 0.92,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Schliemann Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 f5",
                score: 0.66,
                eco: "C63",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Fianchetto Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 g6",
                score: 0.82,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Brentano Gambit",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 g5",
                score: 1.7,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Retreat Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 Nb8",
                score: 1.87,
                eco: "C60",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Bird Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 Nd4",
                score: 0.63,
                eco: "C61",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Pollock Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 Na5",
                score: 1.18,
                eco: "C60",
                __typename: "OpeningNext",
            },
        ],
        from: [
            {
                name: "King's Knight Opening: Normal Variation",
                moves: "1. e4 e5 2. Nf3 Nc6",
                __typename: "OpeningNext",
            },
            {
                name: "Open Game: Portuguese, 2...Nc6",
                moves: "1. e4 e5 2. Bb5 Nc6",
                __typename: "OpeningNext",
            },
        ],
        aliases: ["Spanish (Ruy Lopez)"],
        score: 0.39,
        __typename: "Opening2",
    },
    "r1bqkbnr/1ppp1ppp/p1n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4": {
        eco: "C70",
        name: "Ruy Lopez: Morphy Defense",
        moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6",
        next: [
            {
                name: "Ruy Lopez: Exchange Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Bxc6",
                score: 0.14,
                eco: "C68",
                __typename: "OpeningNext",
            },
            {
                name: "Spanish: 3...a6 4.Bc4",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Bc4",
                score: 0.06,
                eco: "C68",
                __typename: "OpeningNext",
            },
            {
                name: "Spanish: 4.Ba4",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4",
                score: 0.42,
                eco: "C70",
                __typename: "OpeningNext",
            },
        ],
        from: [
            {
                name: "Ruy Lopez",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5",
                __typename: "OpeningNext",
            },
        ],
        aliases: ["Spanish: 3...a6", "Ruy Lopez, 2. Nf3 Nc6 3. Bb5 a6"],
        score: 0.29,
        __typename: "Opening2",
    },
    "r1bqkbnr/1ppp1ppp/p1n5/4p3/B3P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 1 4": {
        eco: "C70",
        name: "Spanish: 4.Ba4",
        moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4",
        next: [
            {
                name: "Spanish: 4.Ba4 Be7",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Be7",
                score: 0.39,
                eco: "C70",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Classical Defense Deferred",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Bc5",
                score: 0.16,
                eco: "C70",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Alapin's Defense Deferred",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Bb4",
                score: 1.28,
                eco: "C70",
                __typename: "OpeningNext",
            },
            {
                name: "Spanish: Morphy Defence",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6",
                score: 0.5,
                eco: "C77",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Cozio Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nge7",
                score: 0.62,
                eco: "C70",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Caro Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 b5",
                score: 0.37,
                eco: "C70",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Modern Steinitz Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 d6",
                score: 0.77,
                eco: "C71",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Schliemann Defense Deferred",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 f5",
                score: 1.62,
                eco: "C70",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Fianchetto Defense Deferred",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 g6",
                score: 0.75,
                eco: "C70",
                __typename: "OpeningNext",
            },
            {
                name: "Spanish: Brentano Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 g5",
                score: 1.84,
                eco: "C70",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Bird's Defense Deferred",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nd4",
                score: 1.05,
                eco: "C70",
                __typename: "OpeningNext",
            },
        ],
        from: [
            {
                name: "Ruy Lopez: Morphy Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6",
                __typename: "OpeningNext",
            },
        ],
        aliases: ["Ruy Lopez: Columbus Variation"],
        score: 0.42,
        __typename: "Opening2",
    },
    "r1bqkb1r/1ppp1ppp/p1n2n2/4p3/B3P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 2 5": {
        eco: "C77",
        name: "Spanish: Morphy Defence",
        moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6",
        next: [
            {
                name: "Ruy Lopez: Morphy Defense, Bayreuth Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. Bxc6",
                score: 0.15,
                eco: "C77",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Jaffe Gambit",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. c3",
                score: -0.06,
                eco: "C77",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Anderssen Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. d3",
                score: 0.08,
                eco: "C77",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Mackenzie Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. d4",
                score: 0.11,
                eco: "C77",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Tarrasch Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. Nc3",
                score: 0.36,
                eco: "C77",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Wormald Attack",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. Qe2",
                score: -0.04,
                eco: "C77",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O",
                score: 0.31,
                eco: "C78",
                __typename: "OpeningNext",
            },
        ],
        from: [
            {
                name: "Spanish: 4.Ba4",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4",
                __typename: "OpeningNext",
            },
        ],
        aliases: [],
        score: 0.5,
        __typename: "Opening2",
    },
    "r1bqkb1r/1ppp1ppp/p1n2n2/4p3/B3P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 3 5": {
        eco: "C78",
        name: "Ruy Lopez: Morphy Defense",
        moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O",
        next: [
            {
                name: "Ruy Lopez: Closed",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Be7",
                score: 0.28,
                eco: "C84",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Neo-Arkhangelsk Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Bc5",
                score: 0.45,
                eco: "C78",
                __typename: "OpeningNext",
            },
            {
                name: "Spanish: 5.O-O b5",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O b5",
                score: 0.37,
                eco: "C78",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Morphy Defense, Steinitz Deferred",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O d6",
                score: 0.56,
                eco: "C79",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Central Countergambit",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O d5",
                score: 2.97,
                eco: "C78",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Brix Variation",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O g6",
                score: 1.66,
                eco: "C78",
                __typename: "OpeningNext",
            },
            {
                name: "Ruy Lopez: Open",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Nxe4",
                score: 0.38,
                eco: "C80",
                __typename: "OpeningNext",
            },
        ],
        from: [
            {
                name: "Spanish: Morphy Defence",
                moves: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6",
                __typename: "OpeningNext",
            },
        ],
        aliases: ["Spanish: 5.O-O"],
        score: 0.31,
        __typename: "Opening2",
    },
    unknown: {
        eco: "F00",
        moves: "1. i4",
        name: "No Pawn Game",
        next: [],
        from: [],
        aliases: [],
        score: -99.0,
    },
};

/* Note that the sites argument values are omitted and assumed to be ["FICS", "lichess"] */
const altOpening = {
    "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1": {
        alsoKnownAs: [null, "King's Pawn Game"],
        wins: [
            {
                w: 158841,
                b: 117423,
                d: 108384,
                __typename: "Wins",
            },
            {
                w: 372266,
                b: 280238,
                d: 486092,
                __typename: "Wins",
            },
        ],
        __typename: "AltOpening",
    },
    "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2": {
        alsoKnownAs: [null, "King's Pawn Game"],
        wins: [
            {
                w: 54036,
                b: 38727,
                d: 43256,
                __typename: "Wins",
            },
            {
                w: 78492,
                b: 53926,
                d: 126510,
                __typename: "Wins",
            },
        ],
        __typename: "AltOpening",
    },
    "rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2": {
        alsoKnownAs: ["Open Game", "King's Knight Opening"],
        wins: [
            {
                w: 48515,
                b: 32401,
                d: 40050,
                __typename: "Wins",
            },
            {
                w: 71489,
                b: 47892,
                d: 117981,
                __typename: "Wins",
            },
        ],
        __typename: "AltOpening",
    },
    "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3": {
        alsoKnownAs: ["Open Game", "King's Knight Opening: Normal Variation"],
        wins: [
            {
                w: 40548,
                b: 29618,
                d: 36243,
                __typename: "Wins",
            },
            {
                w: 61049,
                b: 42877,
                d: 99677,
                __typename: "Wins",
            },
        ],
        __typename: "AltOpening",
    },
    "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3": {
        alsoKnownAs: ["Spanish (Ruy Lopez)", "Ruy Lopez"],
        wins: [
            {
                w: 28416,
                b: 19041,
                d: 23703,
                __typename: "Wins",
            },
            {
                w: 40468,
                b: 25846,
                d: 69001,
                __typename: "Wins",
            },
        ],
        __typename: "AltOpening",
    },
    "r1bqkbnr/1ppp1ppp/p1n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4": {
        alsoKnownAs: ["Spanish: 3...a6", "Ruy Lopez: Morphy Defense"],
        wins: [
            {
                w: 21855,
                b: 13696,
                d: 16744,
                __typename: "Wins",
            },
            {
                w: 29861,
                b: 19094,
                d: 48756,
                __typename: "Wins",
            },
        ],
        __typename: "AltOpening",
    },
    "r1bqkbnr/1ppp1ppp/p1n5/4p3/B3P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 1 4": {
        alsoKnownAs: ["Spanish: 4.Ba4", ""],
        wins: [
            {
                w: 20343,
                b: 11924,
                d: 15617,
                __typename: "Wins",
            },
            {
                w: 27329,
                b: 17112,
                d: 43778,
                __typename: "Wins",
            },
        ],
        __typename: "AltOpening",
    },
    "r1bqkb1r/1ppp1ppp/p1n2n2/4p3/B3P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 2 5": {
        alsoKnownAs: ["Spanish: Morphy Defence", ""],
        wins: [
            {
                w: 17940,
                b: 10835,
                d: 14440,
                __typename: "Wins",
            },
            {
                w: 24240,
                b: 14933,
                d: 40472,
                __typename: "Wins",
            },
        ],
        __typename: "AltOpening",
    },
    "r1bqkb1r/1ppp1ppp/p1n2n2/4p3/B3P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 3 5": {
        alsoKnownAs: ["Spanish: 5.O-O", "Ruy Lopez: Morphy Defense"],
        wins: [
            {
                w: 17751,
                b: 10073,
                d: 13883,
                __typename: "Wins",
            },
            {
                w: 21050,
                b: 12373,
                d: 36502,
                __typename: "Wins",
            },
        ],
        __typename: "AltOpening",
    },
};

const similarOpening = {
"r1bqkb1r/1ppp1ppp/p1n2n2/4p3/B3P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 3 5": [
    {
      "fen": "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQ1RK1 b kq - 2 5",
      "simScore": 27,
      "name": "Giuoco Pianissimo: 4.d3 Nf6 5.O-O",
      "__typename": "SimilarOpening"
    },
    {
      "fen": "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2P2N2/PP1P1PPP/RNBQ1RK1 b kq - 2 5",
      "simScore": 27,
      "name": "Giuoco Piano: Albin Gambit",
      "__typename": "SimilarOpening"
    },
    {
      "fen": "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2P2N2/PP1P1PPP/RNBQ1RK1 b kq - 0 5",
      "simScore": 27,
      "name": "Italian Game: Classical Variation, Albin Gambit",
      "__typename": "SimilarOpening"
    },
    {
      "fen": "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 b kq - 7 5",
      "simScore": 27,
      "name": "Giuoco Piano: 4.O-O Nf6 5.Nc3",
      "__typename": "SimilarOpening"
    },
    {
      "fen": "r1bqkb1r/pppp1ppp/2n2n2/8/2BpP3/5N2/PPP2PPP/RNBQ1RK1 b kq - 3 5",
      "simScore": 26,
      "name": "Scotch Game: Scotch Gambit (i)",
      "__typename": "SimilarOpening"
    },
    {
      "fen": "r1bqkb1r/pppp1ppp/2n2n2/8/2BpP3/5N2/PPP2PPP/RNBQ1RK1 b kq - 1 5",
      "simScore": 26,
      "name": "Italian Game: Scotch Gambit",
      "__typename": "SimilarOpening"
    },
    {
      "fen": "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2BPP3/5N2/PPP2PPP/RNBQ1RK1 b kq - 0 5",
      "simScore": 26,
      "name": "Italian Game: Deutz Gambit",
      "__typename": "SimilarOpening"
    },
    {
      "fen": "r1bqk2r/pppp1ppp/2n2n2/1Bb1p3/4P3/2P2N2/PP1P1PPP/RNBQ1RK1 b kq - 0 5",
      "simScore": 26,
      "name": "Ruy Lopez: Classical Variation, Zukertort Gambit",
      "__typename": "SimilarOpening"
    },
    {
      "fen": "r1bqk2r/pppp1ppp/2n2n2/1Bb1p3/4P3/2N2N2/PPPP1PPP/R1BQ1RK1 b kq - 7 5",
      "simScore": 26,
      "name": "Four Knights: Spanish, Classical Defence, 5.O-O",
      "__typename": "SimilarOpening"
    }
  ]
}

export { opening2, altOpening, similarOpening };
